package org.jdesktop.wonderland.modules.inventory.client;

import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextPane;

/**
 * GUI for user to see list of items in his/her inventory.
 *
 * Code based on ItemPanel by
 *
 * @author Pirmin Riedmann
 *
 * adapted by
 * @author Lisa Tomes <lisa.tomes@student.tugraz.at>
 */
public class ItemPanel extends javax.swing.JPanel
{

  public ItemPanel()
  {
    initComponents();
  }

  public JTextPane getTextPane()
  {
    return itemTextPane;
  }

  public JList getList()
  {
    return itemList;
  }

  public JLabel getTitleLabel()
  {
    return titelLabel;
  }

  public JLabel getImageLabel()
  {
    return lbImage;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    itemList = new javax.swing.JList();
    jLabel1 = new javax.swing.JLabel();
    titelLabel = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    itemTextPane = new javax.swing.JTextPane();
    lbImage = new javax.swing.JLabel();

    itemList.setBackground(new java.awt.Color(204, 204, 204));
    itemList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    itemList.setModel(new javax.swing.AbstractListModel()
    {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(itemList);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("Title:");

    titelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    titelLabel.setText("jLabel2");

    itemTextPane.setEditable(false);
    itemTextPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jScrollPane2.setViewportView(itemTextPane);

    lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbImage.setText(" ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(titelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addGap(4, 4, 4))
          .addComponent(jScrollPane2)
          .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel1)
              .addComponent(titelLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JList itemList;
  private javax.swing.JTextPane itemTextPane;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel lbImage;
  private javax.swing.JLabel titelLabel;
  // End of variables declaration//GEN-END:variables
}
