package org.jdesktop.wonderland.modules.itemboard.client;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;

/**
 * GUI for user to see list of items in his/her inventory.
 *
 * Code based on ItemPanel by
 *
 * @author Pirmin Riedmann
 *
 * adapted by
 *
 * @author Lisa Tomes <lisa.tomes@student.tugraz.at>
 */
public class ItemChooserPanel extends javax.swing.JPanel
{

  public DefaultListModel<Item> dlm;

  public ItemChooserPanel(ArrayList<Item> itemEntryList)
  {
    initComponents();

    dlm = new DefaultListModel<Item>();

    for (Item item : itemEntryList)
    {
      dlm.addElement(item);
    }

    itemList.setModel(dlm);

    btOK.setText("OK");
    btCancel.setText("Cancel");
  }

  public Item getSelectedItem()
  {
    int selIndex = itemList.getSelectedIndex();
    if (selIndex > -1 && selIndex < dlm.getSize())
    {
      return dlm.get(selIndex);
    }
    else
    {
      return null;
    }
  }

  public JButton getOKButton()
  {
    return btOK;
  }

  public JButton getCancelButton()
  {
    return btCancel;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    itemList = new javax.swing.JList();
    btOK = new javax.swing.JButton();
    btCancel = new javax.swing.JButton();

    setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Please choose item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

    itemList.setBackground(new java.awt.Color(204, 204, 204));
    itemList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    itemList.setModel(new javax.swing.AbstractListModel()
    {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(itemList);

    btOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btOK.setText("jButton1");

    btCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    btCancel.setText("jButton2");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btOK)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btCancel)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btOK)
          .addComponent(btCancel))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btCancel;
  private javax.swing.JButton btOK;
  private javax.swing.JList itemList;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
